// Shared mock data with internet sample products and real photography for Oitijjo platform

export const CRAFTS = [
  { 
    id: 'nakshi',  
    label: 'নকশিকাঁথা',  
    labelEn: 'Nakshi Kantha',  
    icon: '🪡', 
    color: '#c0522b',
    heroImage: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=800&q=80',
    description: 'গ্রামীণ নারীদের নিপুণ হাতের সুই-সুতোর কারুকাজ'
  },
  { 
    id: 'tant',    
    label: 'তাঁত শিল্প',   
    labelEn: 'Tant Weaving',   
    icon: '🧶', 
    color: '#8a6a1a',
    heroImage: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    description: 'টাঙ্গাইল ও ঢাকার ঐতিহ্যবাহী হ্যান্ডলুম বুনন'
  },
  { 
    id: 'pottery', 
    label: 'মৃৎশিল্প',     
    labelEn: 'Pottery & Terracotta', 
    icon: '🏺', 
    color: '#8b1a1a',
    heroImage: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    description: 'লালমাটি ও কুমার সম্প্রদায়ের প্রাচীন পোড়ামাটির রূপ'
  },
  { 
    id: 'shital',  
    label: 'শীতলপাটি',     
    labelEn: 'Shital Pati',    
    icon: '🌿', 
    color: '#2d6a4f',
    heroImage: 'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?auto=format&fit=crop&w=800&q=80',
    description: 'ইউনেস্কো স্বীকৃত সিলেটের শীতল ও মনোমুগ্ধকর মুর্তা বেতি'
  },
];

export const ARTISANS = [
  { 
    id: 1,  
    name: 'রহিমা বেগম',    
    craft: 'nakshi',  
    region: 'ময়মনসিংহ',  
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=300&q=80',
    icon: '👩', 
    years: 22, 
    verified: true,  
    rating: 4.9,
    salesCount: 142,
    story: 'মা-দাদির কাছ থেকে নকশিকাঁথা বোনা শিখেছি। একটি কাঁথা বুনতে ৩-৪ মাস সময় লাগে, প্রতিটি ফোঁড়ে মিশে থাকে পরিবারের সুখ-দুঃখের স্মৃতি।' 
  },
  { 
    id: 2,  
    name: 'করিম বশাক',    
    craft: 'tant',    
    region: 'টাঙ্গাইল (পাথরাইল)',   
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=300&q=80',
    icon: '👴', 
    years: 35, 
    verified: true,  
    rating: 4.8,
    salesCount: 289,
    story: 'আমরা বসাক বংশের তাঁতি। চার পুরুষ ধরে এই খটখটি তাঁতের মাকু চালিয়ে আসছি। সুতির কোমলতা আর নিখুঁত পাড়ের নকশাই আমাদের অহংকার।' 
  },
  { 
    id: 3,  
    name: 'সুফিয়া খাতুন', 
    craft: 'shital',  
    region: 'সিলেট (বালাগঞ্জ)',      
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=300&q=80',
    icon: '👩', 
    years: 18, 
    verified: true,  
    rating: 5.0,
    salesCount: 95,
    story: 'মুর্তার বন থেকে গভীর ভোরে বেতি সংগ্রহ করি। পানিতে ভিজিয়ে পাতলা ফালি কেটে সম্পূর্ণ প্রাকৃতিক উপায়ে এই শীতলপাটি বোনা হয়।' 
  },
  { 
    id: 4,  
    name: 'হরিপদ পাল',   
    craft: 'pottery', 
    region: 'রায়েরবাজার, ঢাকা', 
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=300&q=80',
    icon: '👨', 
    years: 40, 
    verified: true, 
    rating: 4.7,
    salesCount: 410,
    story: 'মাটির গন্ধেই আমাদের প্রাণ। লালমাটি আর নদীর পলল মাটি মিশিয়ে চাকার ঘূর্ণনে টেরাকোটা ও নিত্যপ্রয়োজনীয় পাত্র রূপ পায়।' 
  },
  { 
    id: 5,  
    name: 'মর্জিনা আক্তার',  
    craft: 'nakshi',  
    region: 'জামালপুর',   
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=300&q=80',
    icon: '👩', 
    years: 15, 
    verified: true,  
    rating: 4.9,
    salesCount: 88,
    story: 'জামালপুরের ঐতিহ্যবাহী সূচিশিল্প সারা দেশে পৌঁছে দিতে পেরে গর্ববোধ করি। প্রতিটি কাঁথায় থাকে প্রকৃতির নানা রূপ।' 
  },
  { 
    id: 6,  
    name: 'জব্বার মিয়া',  
    craft: 'tant',    
    region: 'নাগরপুর, টাঙ্গাইল',    
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=300&q=80',
    icon: '👨', 
    years: 28, 
    verified: true,  
    rating: 4.8,
    salesCount: 174,
    story: 'খাঁটি দেশি সুতো দিয়ে তৈরি হয় জামদানি ও বালুচরি মোটিফের টাঙ্গাইল শাড়ি। আমাদের শাড়ি পরে দেশের নারীরা ঐতিহ্য ধারণ করেন।' 
  },
  { 
    id: 7,  
    name: 'মণিন্দ্র কুমার রুদ্রপাল',   
    craft: 'pottery', 
    region: 'বগুড়া', 
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&w=300&q=80',
    icon: '👨', 
    years: 32, 
    verified: true, 
    rating: 4.9,
    salesCount: 130,
    story: 'মহাস্থানগড়ের হাজার বছরের প্রাচীন টেরাকোটা ঐতিহ্যের অনুপ্রেরণায় আধুনিক গৃহসজ্জার জন্য দেয়াল প্লেট ও ভাস্কর্য তৈরি করি।' 
  },
  { 
    id: 8,  
    name: 'প্রীতি রাণী দে', 
    craft: 'shital',  
    region: 'সুনামগঞ্জ',      
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?auto=format&fit=crop&w=300&q=80',
    icon: '👩', 
    years: 20, 
    verified: true,  
    rating: 4.9,
    salesCount: 64,
    story: 'ইউনেস্কোর ইনট্যাঞ্জিবল কালচারাল হেরিটেজ তালিকাভুক্ত আমাদের শীতলপাটি পরিবেশবান্ধব ও চিরসবুজ।' 
  },
];

export const PRODUCTS = [
  // 1. Nakshi Kantha Products
  { 
    id: 1,  
    artisanId: 1, 
    name: 'ময়ূরপঙ্খী লাল-সোনালি নকশিকাঁথা',   
    craft: 'nakshi',  
    price: 3400, 
    originalPrice: 4200,
    region: 'ময়মনসিংহ',  
    emoji: '🪡', 
    image: 'https://images.unsplash.com/photo-1606744837616-56c9a5c6a6eb?auto=format&fit=crop&w=800&q=80',
    heritage: true,  
    rating: 4.9,
    reviewsCount: 38,
    stock: 4,
    material: '১০০% সুতি কাপড় ও রেশমি সুতো',
    size: '৭.৫ ফুট × ৫.৫ ফুট (ডাবল বেড)',
    timeToMake: '৩ মাস',
    desc: 'হাতে বোনা খাঁটি ৫ স্তরের সুতির কাপড়ে ময়ূর ও পদ্মফুলের ঐতিহ্যবাহী মোটিফ। লাল ও সোনালি রেশমি সুতোয় দৃষ্টিনন্দন রানিং স্টিচ।'  
  },
  { 
    id: 2,  
    artisanId: 5, 
    name: 'সবুজ বনলতা নকশিকাঁথা ওয়ালম্যাট',      
    craft: 'nakshi',  
    price: 1950, 
    originalPrice: 2400,
    region: 'জামালপুর',   
    emoji: '🪡', 
    image: 'https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80',
    heritage: true,  
    rating: 4.8,
    reviewsCount: 22,
    stock: 7,
    material: 'খাঁটি হ্যান্ডলুম কটন ও নকশি সুতো',
    size: '৩ ফুট × ৪ ফুট',
    timeToMake: '১ মাস',
    desc: 'লিভিং রুম বা ড্রয়িং রুমের দেওয়াল সাজানোর জন্য জামালপুরের বিখ্যাত ফুল-পাতা মোটিফে সূক্ষ্ম কাজের ওয়ালম্যাট।'             
  },
  { 
    id: 3,  
    artisanId: 1, 
    name: 'নীলপদ্ম রাজকীয় নকশিকাঁথা (বেবি সেট)',   
    craft: 'nakshi',  
    price: 1450, 
    originalPrice: 1800,
    region: 'ময়মনসিংহ',  
    emoji: '🪡', 
    image: 'https://images.unsplash.com/photo-1607604276583-eef5d076aa5f?auto=format&fit=crop&w=800&q=80',
    heritage: false,  
    rating: 5.0,
    reviewsCount: 45,
    stock: 12,
    material: 'নরম অর্গানিক সুতি',
    size: '৩.৫ ফুট × ২.৫ ফুট',
    timeToMake: '১৫ দিন',
    desc: 'শিশুদের উপযোগী অত্যন্ত নরম ও আরামদায়ক নকশিকাঁথা। কোনো কৃত্রিম রং বা ক্ষতিকারক উপাদান ছাড়া প্রাকৃতিক সুতোয় বোনা।'  
  },

  // 2. Tant & Handloom Saree Products
  { 
    id: 4,  
    artisanId: 2, 
    name: 'নীলাম্বরী খাঁটি টাঙ্গাইল সুতি শাড়ি',   
    craft: 'tant',    
    price: 3600, 
    originalPrice: 4500,
    region: 'টাঙ্গাইল',   
    emoji: '🧶', 
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=800&q=80',
    heritage: true,  
    rating: 4.9,
    reviewsCount: 52,
    stock: 5,
    material: '৮০ কাউন্ট খাঁটি কটন সুতো',
    size: '১২ হাত (ব্লাউজ পিস সহ)',
    timeToMake: '৭ দিন',
    desc: 'হ্যান্ডলুমে বোনা ঐতিহ্যবাহী নীল টাঙ্গাইল শাড়ি। আঁচল ও জমিনে ভোমরা ও তারার সূক্ষ্ম জ্যাকার্ড ডিজাইন।'             
  },
  { 
    id: 5,  
    artisanId: 6, 
    name: 'রাজমহল সোনালি পাড় জামদানি মোটিফ শাড়ি',        
    craft: 'tant',    
    price: 5200, 
    originalPrice: 6500,
    region: 'নাগরপুর',    
    emoji: '🧶', 
    image: 'https://images.unsplash.com/photo-1617627143750-d86bc21e42bb?auto=format&fit=crop&w=800&q=80',
    heritage: true,  
    rating: 5.0,
    reviewsCount: 19,
    stock: 3,
    material: 'রেশম কটন ও খাঁটি জারি সুতো',
    size: '১২ হাত',
    timeToMake: '১২ দিন',
    desc: 'রাজকীয় অনুষ্ঠানে পরিধানযোগ্য সোনালি জরি পাড়ের টাঙ্গাইল শাড়ি। প্রাচীন রাজবাড়ির নকশাশৈলীতে অনুপ্রাণিত।'  
  },
  { 
    id: 6,  
    artisanId: 2, 
    name: 'হাফ-সিল্ক ডব্লি চেক টাঙ্গাইল শাড়ি',        
    craft: 'tant',    
    price: 2850, 
    originalPrice: 3400,
    region: 'টাঙ্গাইল',    
    emoji: '🧶', 
    image: 'https://images.unsplash.com/photo-1583391733956-3750e0ff4e8b?auto=format&fit=crop&w=800&q=80',
    heritage: false,  
    rating: 4.7,
    reviewsCount: 29,
    stock: 8,
    material: 'হাফ সিল্ক ও সুতি ব্লেন্ড',
    size: '১২ হাত',
    timeToMake: '৫ দিন',
    desc: 'দৈনন্দিন অফিস কিংবা ঘরোয়া আয়োজনে পরার জন্য অত্যন্ত হালকা ও আরামদায়ক আধুনিক চেক টাঙ্গাইল শাড়ি।'  
  },

  // 3. Shital Pati Products
  { 
    id: 7,  
    artisanId: 3, 
    name: 'সিলেটের ঐতিহ্যবাহী নকশিপাটি (ডাবল বেড)',         
    craft: 'shital',  
    price: 3800, 
    originalPrice: 4800,
    region: 'সিলেট',      
    emoji: '🌿', 
    image: 'https://images.unsplash.com/photo-1590402494682-cd3fb53b1f70?auto=format&fit=crop&w=800&q=80',
    heritage: true,  
    rating: 5.0,
    reviewsCount: 34,
    stock: 4,
    material: 'খাঁটি মুর্তা বেতি (প্রাকৃতিক ফাইবার)',
    size: '৭ ফুট × ৫ ফুট',
    timeToMake: '১ মাস',
    desc: 'ইউনেস্কো স্বীকৃত সিলেটের ঐতিহ্যবাহী হস্তনির্মিত নকশিপাটি। গরমের দিনে বিছানায় দেবে পরম শান্তি ও প্রাকৃতিক শীতলতা।'         
  },
  { 
    id: 8,  
    artisanId: 8, 
    name: 'শীতলপাটি ডাইনিং টেবিল রানার ও ম্যাট সেট',              
    craft: 'shital',  
    price: 1650, 
    originalPrice: 2100,
    region: 'সুনামগঞ্জ',      
    emoji: '🌿', 
    image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?auto=format&fit=crop&w=800&q=80',
    heritage: true,  
    rating: 4.8,
    reviewsCount: 16,
    stock: 10,
    material: 'চিকন মুর্তা বেতি',
    size: 'রানার (১টি) + ৬টি প্লেসম্যাট',
    timeToMake: '৮ দিন',
    desc: 'আধুনিক ডাইনিং টেবিলের শোভা বাড়াতে পরিবেশবান্ধব ও সহজে পরিষ্কারযোগ্য শীতলপাটির তৈরি টেবিল সেট।'            
  },
  { 
    id: 9,  
    artisanId: 3, 
    name: 'হস্তশিল্প শীতলপাটি ফ্লোর আসন ম্যাট',              
    craft: 'shital',  
    price: 950, 
    originalPrice: 1200,
    region: 'সিলেট',      
    emoji: '🌿', 
    image: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?auto=format&fit=crop&w=800&q=80',
    heritage: false,  
    rating: 4.9,
    reviewsCount: 25,
    stock: 15,
    material: 'মুর্তা গাছের বাকল',
    size: '২.৫ ফুট × ২.৫ ফুট (২টি জোড়া)',
    timeToMake: '৪ দিন',
    desc: 'পূজা-পার্বণ, প্রার্থনা কিংবা ফ্লোর সিটিংয়ের জন্য তৈরি প্রাকৃতিক শীতলপাটির বসার আসন।'            
  },

  // 4. Pottery & Terracotta Products
  { 
    id: 10,  
    artisanId: 4, 
    name: 'টেরাকোটা মাটির রাজকীয় ফুলদানি সেট',          
    craft: 'pottery', 
    price: 1250, 
    originalPrice: 1600,
    region: 'রায়েরবাজার, ঢাকা',       
    emoji: '🏺', 
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?auto=format&fit=crop&w=800&q=80',
    heritage: true, 
    rating: 4.8,
    reviewsCount: 41,
    stock: 9,
    material: 'পোড়ামাটি (Terracotta)',
    size: 'উচ্চতা: ১৪ ইঞ্চি ও ১০ ইঞ্চি (২টি সেট)',
    timeToMake: '৫ দিন',
    desc: 'লালমাটি দিয়ে তৈরি এবং রোদে শুকিয়ে ভাটায় পোড়ানো অ্যান্টিক ফিনিশের ফুলদানি। গৃহকোণে এনে দেয় ঐতিহ্যের ছোঁয়া।'                          
  },
  { 
    id: 11,  
    artisanId: 7, 
    name: 'মহাস্থানগড় মোটিফ মাটির টেরাকোটা ওয়াল প্লেট',            
    craft: 'pottery', 
    price: 850, 
    originalPrice: 1100,
    region: 'বগুড়া', 
    emoji: '🏺', 
    image: 'https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?auto=format&fit=crop&w=800&q=80',
    heritage: true, 
    rating: 4.9,
    reviewsCount: 30,
    stock: 11,
    material: 'প্রাকৃতিক লাল মাটি ও মাটির রং',
    size: 'ব্যাস: ১২ ইঞ্চি',
    timeToMake: '৪ দিন',
    desc: 'প্রাচীন বাংলার পুণ্ড্রবর্ধন ও মহাস্থানগড়ের ভাস্কর্য অনুসরণে তৈরি দেওয়াল সাজানোর টেরাকোটা প্লেট।'                     
  },
  { 
    id: 12,  
    artisanId: 4, 
    name: 'রান্না ও খাবার পরিবেশনের মাটির হাঁড়ি ও বাটি সেট',            
    craft: 'pottery', 
    price: 1100, 
    originalPrice: 1450,
    region: 'রায়েরবাজার, ঢাকা', 
    emoji: '🏺', 
    image: 'https://images.unsplash.com/photo-1612196808214-b8e1d6145a8c?auto=format&fit=crop&w=800&q=80',
    heritage: false, 
    rating: 4.7,
    reviewsCount: 57,
    stock: 20,
    material: 'খাদ্য-উপযোগী প্রাকৃতিক মাটি (লেড-মুক্ত)',
    size: '১টি বড় হাঁড়ি (২ লিটার) + ৪টি মাটির বাটি',
    timeToMake: '৬ দিন',
    desc: 'ঐতিহ্যবাহী মাটির পাতিলে রান্না করলে খাবারের আসল স্বাদ ও পুষ্টিগুণ অটুট থাকে। সম্পূর্ণ রাসায়নিকমুক্ত।'                     
  },
];

export const REGIONS = [
  { id: 1, name: 'টাঙ্গাইল',    crafts: ['তাঁত শিল্প'],           artisans: 12000, lat: 24.25, lon: 89.92 },
  { id: 2, name: 'সিলেট',       crafts: ['শীতলপাটি'],             artisans: 8000,  lat: 24.90, lon: 91.87 },
  { id: 3, name: 'ময়মনসিংহ',   crafts: ['নকশিকাঁথা'],           artisans: 15000, lat: 24.75, lon: 90.40 },
  { id: 4, name: 'রাজশাহী',     crafts: ['নকশিকাঁথা', 'তাঁত'],  artisans: 9000,  lat: 24.37, lon: 88.60 },
  { id: 5, name: 'রায়েরবাজার', crafts: ['মৃৎশিল্প'],             artisans: 3000,  lat: 23.72, lon: 90.34 },
  { id: 6, name: 'বগুড়া',       crafts: ['মৃৎশিল্প'],             artisans: 4500,  lat: 24.84, lon: 89.37 },
  { id: 7, name: 'জামালপুর',     crafts: ['নকশিকাঁথা'],           artisans: 11000, lat: 24.93, lon: 89.94 },
  { id: 8, name: 'সুনামগঞ্জ',   crafts: ['শীতলপাটি'],             artisans: 5500,  lat: 25.06, lon: 91.40 },
];
